#config_version=4
# ONLY INFINITE, ALWAYS DISPLAYED SHOWS GO HERE
show_player:
  init_done:
    general_illumination_fade:
      action: play
  ball_ending{current_player.extra_balls>0}:
    shoot_again_dmd:
      loops: 0
