#config_version=4
sound_player:
  mode_attract_started:
    attract_bgm:
      action: play
  mode_attract_stopped:
    attract_bgm:
      action: stop
  mode_base_started:
    base_bgm:
      action: play
  mode_base_stopped:
    base_bgm:
      action: stop
  mode_multiball_started:
    multiball_bgm:
      action: play
    base_bgm:
      action: stop
  mode_multiball_stopped:
    multiball_bgm:
      action: stop
    base_bgm:
      action: play
  mode_high_score_started:
    high_score_bgm:
      action: play
  # carry song through both modes
  mode_game_over_stopped:
    high_score_bgm:
      action: stop
