#config_version=4
widget_player:
  mode_attract_started:
    title:
      action: add
      widget_settings:
        anchor_y: top
        y: top-4%
    credit:
      action: add
      widget_settings:
        anchor_y: top
        y: top-44%
    company:
      action: add
      widget_settings:
        anchor_y: top
        y: top-70%
    current_score:
      action: remove # when a game ends...
    player_up:
      action: remove
    ball_count:
      action: remove
    player_one_score:
      action: remove
    player_two_score:
      action: remove
    game_over:
      action: remove
  mode_base_started:
    current_score:
      action: add
      widget_settings:
        anchor_y: middle
        anchor_x: center
        y: middle+6%
    player_one_score:
      target: window
      action: add
    player_two_score:
      target: window
      action: add
    player_up:
      action: add
      widget_settings:
        anchor_y: bottom+1%
        anchor_x: left
        y: bottom+4%
        x: left+3%
    ball_count:
      action: add
      widget_settings:
        anchor_y: bottom+1%
        anchor_x: right
        y: bottom+4%
        x: right-1%
    title:
      action: remove
    credit:
      action: remove
    company:
      action: remove
  mode_game_over_started:
    player_one_score:
      target: window
      action: update
    player_two_score:
      target: window
      action: update
    current_score:
      action: remove
    player_up:
      action: remove
    ball_count:
      action: remove
    title:
      action: remove
    credit:
      action: remove
    company:
      action: remove
    game_over:
      action: add
