#config_version=4
high_score:
  _overwrite: True
  categories:
  - score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
  defaults:
    score:
      - ZAC: 999999
      - CAR: 99999
      - RIA: 9999
      - COM: 999
      - BAT: 99

sound_player:
  mode_high_score_started:
    high_score_bgm:
      action: play
  mode_high_score_stopped:
    high_score_bgm:
      action: stop
