#config_version=6
high_score:
  _overwrite: True
  categories:
    score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
  defaults:
    score:
      - ZAC: 240000
      - CAR: 200000
      - RIA: 150000
      - COM: 100000
      - BAT: 50000
