#config_version=5
high_score:
  _overwrite: True
  categories:
  - score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
  defaults:
    score:
      - ZAC: 999999
      - CAR: 99999
      - RIA: 9999
      - COM: 999
      - BAT: 99
