#config_version=5
ball_devices:
  bd_trough:
    ball_switches:
      s_trough_1
      s_trough_2
    tags:
      trough
      home
      drain
    eject_timeouts: 1s
    eject_coil: c_trough_eject
    eject_targets: bd_shooter_lane
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    auto_fire_on_unexpected_ball: false
    ball_search_order: 3
    debug: true
  bd_shooter_lane:
    ball_switches: s_shooter_lane
    mechanical_eject: true
  bd_gun:
    ball_capacity: 1
    entrance_switch: s_kicker_gun
    # eject doesn't work because the switch immediately
    # opens after rolling over and MPF thinks the ball
    # has already left
    eject_timeouts: 1s
    eject_coil: c_kicker_gun
    eject_targets: playfield
    ball_search_order: 1
    debug: true
  bd_missile:
    ball_capacity: 1
    entrance_switch: s_kicker_missile
    eject_timeouts: 1s
    eject_coil: c_kicker_missile
    eject_targets: playfield
    ball_search_order: 2
    debug: true
