#config_version=4
ball_devices:
  bd_trough:
    ball_switches:
      s_trough_1
      s_trough_2
    tags:
      trough
      home
      drain
      ball_add_live
    eject_coil: c_trough_eject
    eject_targets: playfield
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    debug: true
  bd_gun:
    ball_capacity: 1
    entrance_switch: s_kicker_gun
    eject_coil: c_kicker_gun
    eject_targets: playfield
    eject_timeouts: 5s
    debug: true
  bd_missile:
    ball_capacity: 1
    entrance_switch: s_kicker_missile
    eject_coil: c_kicker_missile
    eject_targets: playfield
    eject_timeouts: 3s
    debug: true
