#config_version=4
ball_devices:
  bd_trough:
    ball_switches:
      s_trough_1
      s_trough_2
    tags:
      trough
      home
      drain
      ball_add_live
    eject_timeouts: 1s
    eject_coil: c_trough_eject
    eject_targets: playfield
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    auto_fire_on_unexpected_ball: false
    debug: true
  bd_gun:
    ball_capacity: 1
    entrance_switch: s_kicker_gun
    # eject doesn't work because the switch immediately
    # opens after rolling over and MPF thinks the ball
    # has already left
    eject_timeouts: 1s
    eject_coil: c_kicker_gun
    eject_targets: playfield
    debug: true
  bd_missile:
    ball_capacity: 1
    entrance_switch: s_kicker_missile
    eject_timeouts: 1s
    eject_coil: c_kicker_missile
    eject_targets: playfield
    debug: true
