#config_version=4
coils:
  c_trough_eject:
    number: 0-2
    pulse_ms: 40
  c_flipper_main_1:
    number: 0-6
    pulse_ms: 35
    pulse_power: 7
  c_flipper_hold_1:
    number: 0-7
    allow_enable: true
  c_flipper_main_2:
    number: 0-5
    pulse_ms: 35
    pulse_power: 7
  c_flipper_hold_2:
    number: 0-4
    allow_enable: true
  c_bumper_1:
    number: 1-3
    pulse_ms: 40
  c_bumper_2:
    number: 1-2
    pulse_ms: 40
  c_bumper_3:
    number: 1-1
    pulse_ms: 40
  c_slingshot_1:
    number: 1-0
    pulse_ms: 40
    pulse_power: 7
  c_slingshot_2:
    number: 2-0
    pulse_ms: 40
    pulse_power: 7
  c_kicker_missile:
    number: 2-2
    pulse_ms: 80
    pulse_power: 8
  c_kicker_gun:
    number: 0-0
    pulse_ms: 60
  c_knocker:
    number: 2-1
    pulse_ms: 40
  c_drop_target:
    number: 0-1
    pulse_ms: 100
