#config_version=4
leds:
  l_gi_top_1:
    number:
  l_gi_top_2:
    number:
  l_gi_saucer:
    number:
  l_gi_gun_top:
    number:
  l_gi_spinner:
    number:
  l_gi_gun:
    number:
  l_gi_hole_score_lane:
    number:
  l_gi_advance_bonus:
    number:
  l_gi_advance_hole_score:
    number:
  l_gi_inlane_1:
    number:
  l_gi_inlane_2:
    number:
  l_gi_slingshot_1:
    number:
  l_gi_slingshot_2:
    number:
  l_saucer:
    number: 1-34
  # rename per Steve
  l_spinner:
    number: 1-15
  l_special:
    number: 1-16
  l_bonus_ball_1:
    number: 1-3
  l_bonus_ball_2:
    number: 1-4
  l_shoots_again:
    number: 1-2
  l_bonus_score:
    number: 1-1
  l_bumper_1:
    number: 1-35
  l_bumper_2:
    number: 1-36
  l_bumper_3:
    number: 1-37
  l_rollover_top_1:
    number: 1-30
  l_rollover_top_2:
    number: 1-27
  l_rollover_top_3:
    number: 1-31
  l_rollover_top_4:
    number: 1-28
  l_rollover_top_5:
    number: 1-32
  l_rollover_top_6:
    number: 1-29
  l_rollover_top_7:
    number: 1-33
  l_hole_score_lane_1:
    number: 1-17
  l_hole_score_lane_2:
    number: 1-18
  l_hole_score_lane_3:
    number: 1-19
  l_hole_score_lane_4:
    number: 1-20
  l_hole_score_lane_5:
    number: 1-21
  l_hole_score_lane_6:
    number: 1-22
  l_hole_score_lane_7:
    number: 1-23
  l_hole_score_lane_8:
    number: 1-24
  l_hole_score_lane_9:
    number: 1-25
  l_hole_score_lane_10:
    number: 1-26
  l_explosion_1:
    number: 1-11
  l_explosion_2:
    number: 1-10
  l_explosion_3:
    number: 1-12
  l_explosion_4:
    number: 1-7
  l_explosion_5:
    number: 1-6
  l_explosion_6:
    number: 1-8
  l_explosion_7:
    number: 1-5
  l_explosion_8:
    number: 1-9
  l_explosion_9:
    number: 1-13
  l_explosion_10:
    number: 1-14
