#config_version=5
lights:
  #l_gi_top_1:
  #  number:
  #l_gi_top_2:
  #  number:
  #l_gi_saucer:
  #  number:
  #l_gi_gun_top:
  #  number:
  #l_gi_spinner:
  #  number:
  #l_gi_gun:
  #  number:
  #l_gi_hole_score_lane:
  #  number:
  #l_gi_advance_bonus:
  #  number:
  #l_gi_advance_hole_score:
  #  number:
  #l_gi_inlane_1:
  #  number:
  #l_gi_inlane_2:
  #  number:
  #l_gi_slingshot_1:
  #  number:
  #l_gi_slingshot_2:
  #  number:
  l_spinner:
    number: 0-14
  l_special:
    number: 0-15
  l_bonus_ball_1:
    number: 0-2
  l_bonus_ball_2:
    number: 0-3
  l_shoots_again:
    number: 0-1
  l_bonus_multiplier:
    number: 0-0
  l_bumper_1:
    number: 0-34
  l_bumper_2:
    number: 0-35
  l_bumper_3:
    number: 0-36
  l_missile:
    number: 0-33
  l_rollover_top_1:
    number: 0-29
  l_rollover_top_2:
    number: 0-26
  l_rollover_top_3:
    number: 0-30
  l_rollover_top_4:
    number: 0-27
  l_rollover_top_5:
    number: 0-31
  l_rollover_top_6:
    number: 0-28
  l_rollover_top_7:
    number: 0-32
  l_hole_score_lane_1:
    number: 0-16
  l_hole_score_lane_2:
    number: 0-17
  l_hole_score_lane_3:
    number: 0-18
  l_hole_score_lane_4:
    number: 0-19
  l_hole_score_lane_5:
    number: 0-20
  l_hole_score_lane_6:
    number: 0-21
  l_hole_score_lane_7:
    number: 0-22
  l_hole_score_lane_8:
    number: 0-23
  l_hole_score_lane_9:
    number: 0-24
  l_hole_score_lane_10:
    number: 0-25
  # Explosion Bonus
  l_explosion_1:
    number: 0-10
  l_explosion_2:
    number: 0-9
  l_explosion_3:
    number: 0-11
  l_explosion_4:
    number: 0-6
  l_explosion_5:
    number: 0-5
  l_explosion_6:
    number: 0-7
  l_explosion_7:
    number: 0-4
  l_explosion_8:
    number: 0-8
  l_explosion_9:
    number: 0-12
  l_explosion_10:
    number: 0-13
  # Pop Bumper 1 Ring
  l_bumper1_1:
    number: 1-0
  l_bumper1_2:
    number: 1-1
  l_bumper1_3:
    number: 1-2
  l_bumper1_4:
    number: 1-3
  l_bumper1_5:
    number: 1-4
  l_bumper1_6:
    number: 1-5
  l_bumper1_7:
    number: 1-6
  l_bumper1_8:
    number: 1-7
  l_bumper1_9:
    number: 1-8
  l_bumper1_10:
    number: 1-9
  l_bumper1_11:
    number: 1-10
  l_bumper1_12:
    number: 1-11
  l_bumper1_13:
    number: 1-12
  l_bumper1_14:
    number: 1-13
  l_bumper1_15:
    number: 1-14
  l_bumper1_16:
    number: 1-15
  l_bumper1_17:
    number: 1-16
  l_bumper1_18:
    number: 1-17
  l_bumper1_19:
    number: 1-18
  l_bumper1_20:
    number: 1-19
  l_bumper1_21:
    number: 1-20
  l_bumper1_22:
    number: 1-21
  l_bumper1_23:
    number: 1-22
  l_bumper1_24:
    number: 1-23
  # Pop Bumper 2 Ring
  l_bumper2_1:
    number: 1-24
  l_bumper2_2:
    number: 1-25
  l_bumper2_3:
    number: 1-26
  l_bumper2_4:
    number: 1-27
  l_bumper2_5:
    number: 1-28
  l_bumper2_6:
    number: 1-29
  l_bumper2_7:
    number: 1-30
  l_bumper2_8:
    number: 1-31
  l_bumper2_9:
    number: 1-32
  l_bumper2_10:
    number: 1-33
  l_bumper2_11:
    number: 1-34
  l_bumper2_12:
    number: 1-35
  l_bumper2_13:
    number: 1-36
  l_bumper2_14:
    number: 1-37
  l_bumper2_15:
    number: 1-38
  l_bumper2_16:
    number: 1-39
  l_bumper2_17:
    number: 1-40
  l_bumper2_18:
    number: 1-41
  l_bumper2_19:
    number: 1-42
  l_bumper2_20:
    number: 1-43
  l_bumper2_21:
    number: 1-44
  l_bumper2_22:
    number: 1-45
  l_bumper2_23:
    number: 1-46
  l_bumper2_24:
    number: 1-47
  # Pop Bumper 2 Ring
  l_bumper3_1:
    number: 2-0
  l_bumper3_2:
    number: 2-1
  l_bumper3_3:
    number: 2-2
  l_bumper3_4:
    number: 2-3
  l_bumper3_5:
    number: 2-4
  l_bumper3_6:
    number: 2-5
  l_bumper3_7:
    number: 2-6
  l_bumper3_8:
    number: 2-7
  l_bumper3_9:
    number: 2-8
  l_bumper3_10:
    number: 2-9
  l_bumper3_11:
    number: 2-10
  l_bumper3_12:
    number: 2-11
  l_bumper3_13:
    number: 2-12
  l_bumper3_14:
    number: 2-13
  l_bumper3_15:
    number: 2-14
  l_bumper3_16:
    number: 2-15
  l_bumper3_17:
    number: 2-16
  l_bumper3_18:
    number: 2-17
  l_bumper3_19:
    number: 2-18
  l_bumper3_20:
    number: 2-19
  l_bumper3_21:
    number: 2-20
  l_bumper3_22:
    number: 2-21
  l_bumper3_23:
    number: 2-22
  l_bumper3_24:
    number: 2-23
