#config_version=4
# all switches left to right
switches:
  # TODO
  #s_knocker:
  #  number:
  #  tags: playfield_active
  s_slingshot_1:
    number: 1-3
    tags: playfield_active
  s_slingshot_2:
    number: 0-29
    tags: playfield_active
  s_start:
    # fake number for now
    number: 1-5
    # 'start' tag is important
    tags: start
  # switch inside coin door to activate Config Menu
  #s_menu:
  #  number: 0-0
  # Trough Switches (max 3 balls, "duo-multi" and "extra")
  s_trough_1:
    number: 0-0
    type: NC
  s_trough_2:
    number: 0-1
    type: NC
  s_trough_jam:
    number: 0-2
    type: NC
  s_kicker_saucer:
    number: 0-28
    tags: playfield_active
  s_kicker_gun:
    number: 0-10
    tags: playfield_active
  # Pop Bumpers
  s_bumper_1:
    number: 1-0
    tags: playfield_active
  s_bumper_2:
    number: 1-1
    tags: playfield_active
  s_bumper_3:
    number: 1-2
    tags: playfield_active
  s_flipper_1:
    number: 0-7
  s_flipper_1_eos:
    number: 0-4
  s_flipper_2:
    number: 0-6
  s_flipper_2_eos:
    number: 0-3
  s_spinner:
    number: 0-26
    tags: playfield_active
  s_rollover_top_1:
    number: 0-19
    tags: playfield_active
  s_rollover_top_2:
    number: 0-16
    tags: playfield_active
  s_rollover_top_3:
    number: 0-20
    tags: playfield_active
  s_rollover_top_4:
    number: 0-17
    tags: playfield_active
  s_rollover_top_5:
    number: 0-21
    tags: playfield_active
  s_rollover_top_6:
    number: 0-18
    tags: playfield_active
  s_rollover_top_7:
    number: 0-22
    tags: playfield_active
  s_rollover_bonus_ball_1:
    number: 0-25
    tags: playfield_active
  s_rollover_bonus_ball_2:
    number: 0-5
    tags: playfield_active
  s_rollover_advance_hole_1:
    number: 0-24
    tags: playfield_active
  s_rollover_advance_hole_2:
    number: 0-31
    tags: playfield_active
  s_stationary_thousand:
    number: 0-27
    tags: playfield_active
  s_stationary_special:
    number: 0-14
    tags: playfield_active
  # same switch hit for each of the "B O M B S" targets
  s_drop_target:
    number: 0-11
    tags: playfield_active
  s_drop_target_behind:
    number: 0-12
    tags: playfield_active
  s_drop_target_reset:
    number: 0-13
  s_stationary_advance_bonus:
    number: 0-9
    tags: playfield_active
  s_stationary_advance_hole_score:
    number: 0-8
    tags: playfield_active
