#config_version=5
show_player:
  mode_attract_started:
    # LEDs
    bumper_flash:
      action: play
    hole_score_lane_sweep:
      action: play
    explosion_sweep:
      action: play
    target_triplet:
      action: play
    rollover_top_swap:
      action: play
  mode_attract_stopped:
    bumper_flash:
      action: stop
    hole_score_lane_sweep:
      action: stop
    explosion_sweep:
      action: stop
    target_triplet:
      action: stop
    rollover_top_swap:
      action: stop

sound_player:
  mode_attract_started:
    attract_bgm:
      action: play
  mode_attract_stopped:
    attract_bgm:
      action: stop

widget_player:
  mode_attract_started:
    # DMD
    title:
      action: add
      widget_settings:
        anchor_y: top
        y: top-4%
    credit:
      action: add
      widget_settings:
        anchor_y: top
        y: top-44%
    company:
      action: add
      widget_settings:
        anchor_y: top
        y: top-70%
    current_score:
      action: remove # when a game ends...
    player_up:
      action: remove
    ball_count:
      action: remove
    player_one_score:
      action: remove
    player_two_score:
      action: remove
    game_over:
      action: remove
