#config_version=4
mode:
  start_events: ball_starting
  priority: 100
  code: base.Custom

# blocks reset on completion by default
logic_blocks:
  counters:
    bombs:
      count_events: s_drop_target_active
      starting_count: 5
      count_complete_value: 0
      direction: down
      events_when_complete: bombs_complete
      restart_events: s_drop_target_reset_active
    spins:
      count_events: s_spinner_active
      starting_count: 0
      count_complete_value: 8
      direction: up
      events_when_complete: spins_advance_hole
    hole_score:
      count_events:
        s_rollover_advance_hole_1_active
        s_rollover_advance_hole_2_active
        s_stationary_advance_hole_score_active
        spin_advances_hole
      starting_count: 1
      count_complete_value: 10
      events_when_complete: hole_score_complete
      direction: up
      restart_events: mode_hole_score_stopped
      reset_on_complete: false

sound_player:
  mode_base_started:
    plunging_bgm:
      action: play
  balldevice_playfield_ball_enter:
    plunging_bgm:
      action: stop

shows:
  hole_score_show:
    - duration: -1
      leds:
        l_hole_score_lane_1: '56A20A'
    - duration: -1
      leds:
        l_hole_score_lane_1: '56A20A'
        l_hole_score_lane_2: '56A20A'
    - duration: -1
      leds:
        l_hole_score_lane_1: '56A20A'
        l_hole_score_lane_2: '56A20A'
        l_hole_score_lane_3: '56A20A'
    - duration: -1
      leds:
        l_hole_score_lane_1: '56A20A'
        l_hole_score_lane_2: '56A20A'
        l_hole_score_lane_3: '56A20A'
        l_hole_score_lane_4: 'FF69B4'
    - duration: -1
      leds:
        l_hole_score_lane_1: '56A20A'
        l_hole_score_lane_2: '56A20A'
        l_hole_score_lane_3: '56A20A'
        l_hole_score_lane_4: 'FF69B4'
        l_hole_score_lane_5: 'FF69B4'
    - duration: -1
      leds:
        l_hole_score_lane_1: '56A20A'
        l_hole_score_lane_2: '56A20A'
        l_hole_score_lane_3: '56A20A'
        l_hole_score_lane_4: 'FF69B4'
        l_hole_score_lane_5: 'FF69B4'
        l_hole_score_lane_6: 'FF69B4'
    - duration: -1
      leds:
        l_hole_score_lane_1: '56A20A'
        l_hole_score_lane_2: '56A20A'
        l_hole_score_lane_3: '56A20A'
        l_hole_score_lane_4: 'FF69B4'
        l_hole_score_lane_5: 'FF69B4'
        l_hole_score_lane_6: 'FF69B4'
        l_hole_score_lane_7: 'FFFF00'
    - duration: -1
      leds:
        l_hole_score_lane_1: '56A20A'
        l_hole_score_lane_2: '56A20A'
        l_hole_score_lane_3: '56A20A'
        l_hole_score_lane_4: 'FF69B4'
        l_hole_score_lane_5: 'FF69B4'
        l_hole_score_lane_6: 'FF69B4'
        l_hole_score_lane_7: 'FFFF00'
        l_hole_score_lane_8: 'FFFF00'
    - duration: -1
      leds:
        l_hole_score_lane_1: '56A20A'
        l_hole_score_lane_2: '56A20A'
        l_hole_score_lane_3: '56A20A'
        l_hole_score_lane_4: 'FF69B4'
        l_hole_score_lane_5: 'FF69B4'
        l_hole_score_lane_6: 'FF69B4'
        l_hole_score_lane_7: 'FFFF00'
        l_hole_score_lane_8: 'FFFF00'
        l_hole_score_lane_9: 'FFFF00'
    - duration: -1
      leds:
        l_hole_score_lane_1: '56A20A'
        l_hole_score_lane_2: '56A20A'
        l_hole_score_lane_3: '56A20A'
        l_hole_score_lane_4: 'FF69B4'
        l_hole_score_lane_5: 'FF69B4'
        l_hole_score_lane_6: 'FF69B4'
        l_hole_score_lane_7: 'FFFF00'
        l_hole_score_lane_8: 'FFFF00'
        l_hole_score_lane_9: 'FFFF00'
        l_hole_score_lane_10: 'FF8000'

show_player:
  logicblock_hole_score_updated:
    hole_score_show:
      start_step: current_player.hole_score_count
  mode_hole_score_stopped:
    hole_score_show:
      start_step: 1

event_player:
  # cause the drop target to reset
  # when mode ends event if only
  # partially activated
  mode_bombs_dropped_stopped:
    s_drop_target_reset_active

scoring:
  s_kicker_gun_active:
    score: 5000
  s_bumper_1_active:
    score: 100 # in ask app these were 1000 immediately
  s_bumper_2_active:
    score: 100
  s_bumper_3_active:
    score: 100
  s_slingshot_1_active:
    score: 10
  s_slingshot_2_active:
    score: 10
  s_spinner_active:
    score: 100
  s_rollover_top_1_active:
    score: 500 # in ask app, top 4 gave 5000 and bottom 3 500
  s_rollover_top_2_active:
    score: 500
  s_rollover_top_3_active:
    score: 500
  s_rollover_top_4_active:
    score: 500
  s_rollover_top_5_active:
    score: 500
  s_rollover_top_6_active:
    score: 500
  s_rollover_top_7_active:
    score: 500
  s_rollover_bonus_ball_1_active:
    score: 1000
  s_rollover_bonus_ball_2_active:
    score: 1000
  s_rollover_advance_hole_1_active:
    score: 1000
  s_rollover_advance_hole_2_active:
    score: 1000
  s_stationary_thousand_active:
    score: 1000 # i assume this was the 'left standup'?
  s_stationary_special_active:
    score: 500 # 5k once drop target complete...
  s_drop_target_active:
    score: 1000 # in ask app, these were 5000
  s_drop_target_behind_active:
    score: 500
  s_stationary_advance_bonus_active:
    score: 0
  s_stationary_advance_hole_score_active:
    score: 0
