#config_version=6
mode:
  start_events: timer_start_base_complete
  priority: 100

tilt:
  tilt_warning_switch_tag: tilt_warning
  tilt_switch_tag: tilt
  slam_tilt_switch_tag: slam_tilt
  warnings_to_tilt: 3
  reset_warnings_events: ball_ended
  multiple_hit_window: 300ms
  settle_time: 3s
  tilt_warnings_player_var: tilt_warnings

# drop target counter is here
# so we can ignore the 'reset' and 'hit'
# during the initialization mode
counters:
  bombs:
    count_events: s_drop_target_active
    starting_count: 5
    count_complete_value: 0
    direction: down
    # the reset switch starts laser bombs,
    # either pragmatically or mechanically
    events_when_complete: bombs_complete
    enable_events:
    - mode_base_started
    - mode_bombs_dropped_stopped
    disable_events: mode_bombs_dropped_started
    restart_events:
    - mode_bombs_dropped_stopped

shots:
  shared_drop:
    switch: s_drop_target
  gun_shot:
    switch: s_kicker_gun

event_player:
  # cause the drop target to reset
  # when mode ends event if only
  # partially activated
  s_drop_target_reset_active: bombs_complete

light_player:
  extra_ball_awarded:
    l_shoots_again: orange

sound_player:
  mode_base_started{current_player.ball == 1}:
    base_bgm:
      action: play
  mode_base_started{current_player.ball == 2}:
    base_bgm:
      action: play
      start_at: 50
  mode_base_started{current_player.ball == 3}:
    base_bgm:
      action: play
      start_at: 160
  mode_multiball_stopped:
    base_bgm:
      action: play
      start_at: 16
  mode_base_stopped:
    base_bgm:
      action: stop
  # unique targets
  s_kicker_gun_active: gun_explosion_sfx
  s_bumper_1_active: bullet_ping_pool
  s_bumper_2_active: bullet_ping_pool
  s_bumper_3_active: bullet_ping_pool
  s_spinner_active: shot_and_ping_pool
  # quick gun sound for sounds that may be concurrent
  s_rollover_advance_hole_score_1_active: gun_shot_distant_sfx
  s_rollover_advance_hole_score_2_active: gun_shot_distant_sfx
  s_stationary_advance_hole_score_active: gun_shot_distant_sfx
  # unique pools for 2 main logic blocks
  logicblock_hole_score_updated{value > 0}: missile_advance_pool
  cluster_a_advance_bonus_hit: machine_gun_pool
  cluster_b_advance_bonus_hit: machine_gun_pool
  s_stationary_advance_bonus_active: machine_gun_pool
  # basic explosion sound for everything else
  s_slingshot_1_active: explosion_pool
  s_slingshot_2_active: explosion_pool
  s_rollover_bonus_ball_1_active: explosion_pool
  s_rollover_bonus_ball_2_active: explosion_pool
  s_stationary_thousand_active: explosion_pool
  s_stationary_special_active: explosion_pool
  s_drop_target_active: explosion_pool
  s_drop_target_behind_active: explosion_pool
  extra_ball_awarded: missile_advance_3_sfx

variable_player:
  s_bumper_1_active:
    score: 100 # in ask app these were 1000 immediately
  s_bumper_2_active:
    score: 100
  s_bumper_3_active:
    score: 100
  s_slingshot_1_active:
    score: 10
  s_slingshot_2_active:
    score: 10
  s_spinner_active:
    score: 100
  s_rollover_top_1_active:
    score: 500 # in ask app, top 4 gave 5000 and bottom 3 500
  s_rollover_top_2_active:
    score: 500
  s_rollover_top_3_active:
    score: 500
  s_rollover_top_4_active:
    score: 500
  s_rollover_top_5_active:
    score: 500
  s_rollover_top_6_active:
    score: 500
  s_rollover_top_7_active:
    score: 500
  s_rollover_bonus_ball_1_active:
    score: 1000
  s_rollover_bonus_ball_2_active:
    score: 1000
  s_rollover_advance_hole_1_active:
    score: 1000
  s_rollover_advance_hole_2_active:
    score: 1000
  s_stationary_thousand_active:
    score: 1000 # i assume this was the 'left standup'?
  s_stationary_special_active:
    score: 500 # 5k once drop target complete...
  s_drop_target_active:
    score: 1000 # in ask app, these were 5000
  s_drop_target_behind_active:
    score: 500
  s_stationary_advance_bonus_active:
    score: 100
  s_stationary_advance_hole_score_active:
    score: 100
  s_kicker_gun_active:
    score: 5000
