#config_version=4
mode:
  start_events: ball_starting
  priority: 100

scoring:
  s_kicker_saucer_active:
    score: 0
  s_kicker_gun_active:
    score: 5000
  s_bumper_1_active:
    score: 100 # in ask app these were 1000 immediately
  s_bumper_2_active:
    score: 100
  s_bumper_3_active:
    score: 100
  s_slingshot_1_active:
    score: 100
  s_slingshot_2_active:
    score: 100
  s_spinner_active:
    score: 100
  s_rollover_top_1_active:
    score: 500 # in ask app, top 4 gave 5000 and bottom 3 500
  s_rollover_top_2_active:
    score: 500
  s_rollover_top_3_active:
    score: 500
  s_rollover_top_4_active:
    score: 500
  s_rollover_top_5_active:
    score: 500
  s_rollover_top_6_active:
    score: 500
  s_rollover_top_7_active:
    score: 500
  s_rollover_bonus_ball_1_active:
    score: 1000
  s_rollover_bonus_ball_2_active:
    score: 1000
  s_rollover_advance_hole_1_active:
    score: 1000
  s_rollover_advance_hole_2_active:
    score: 1000
  s_stationary_thousand_active:
    score: 1000 # i assume this was the 'left standup'?
  s_stationary_special_active:
    score: 20000
  s_drop_target_1_active:
    score: 1000 # in ask app, these were 5000
  s_drop_target_2_active:
    score: 1000
  s_drop_target_3_active:
    score: 1000
  s_drop_target_4_active:
    score: 1000
  s_drop_target_5_active:
    score: 1000
  s_stationary_advance_bonus_active:
    score: 0
  s_stationary_advance_hole_score_active:
    score: 0
