#config_version=4
mode:
  start_events: timer_start_base_complete
  priority: 100

# drop target counter is here
# so we can ignore the 'reset' and 'hit'
# during the initialization mode
logic_blocks:
  counters:
    bombs:
      count_events: s_drop_target_active
      starting_count: 5
      count_complete_value: 0
      direction: down
      events_when_complete: bombs_complete
      restart_events: s_drop_target_reset_active

scoring:
  s_bumper_1_active:
    score: 100 # in ask app these were 1000 immediately
  s_bumper_2_active:
    score: 100
  s_bumper_3_active:
    score: 100
  s_slingshot_1_active:
    score: 10
  s_slingshot_2_active:
    score: 10
  s_spinner_active:
    score: 100
  s_rollover_top_1_active:
    score: 500 # in ask app, top 4 gave 5000 and bottom 3 500
  s_rollover_top_2_active:
    score: 500
  s_rollover_top_3_active:
    score: 500
  s_rollover_top_4_active:
    score: 500
  s_rollover_top_5_active:
    score: 500
  s_rollover_top_6_active:
    score: 500
  s_rollover_top_7_active:
    score: 500
  s_rollover_bonus_ball_1_active:
    score: 1000
  s_rollover_bonus_ball_2_active:
    score: 1000
  s_rollover_advance_hole_1_active:
    score: 1000
  s_rollover_advance_hole_2_active:
    score: 1000
  s_stationary_thousand_active:
    score: 1000 # i assume this was the 'left standup'?
  s_stationary_special_active:
    score: 500 # 5k once drop target complete...
  s_drop_target_active:
    score: 1000 # in ask app, these were 5000
  s_drop_target_behind_active:
    score: 500
  s_stationary_advance_bonus_active:
    score: 100
  s_stationary_advance_hole_score_active:
    score: 100
  s_kicker_gun_active:
    score: 5000
