#config_version=6
# actived when all 5 drop targets have dropped
# user wants to continue hitting those
# hitting the special kills the mode
mode:
  start_events: ball_hold_gun_multi_full
  priority: 150
  code: multiball.Custom
  stop_events: multiball_multi_bombs_ball_lost

multiballs:
  multi_bombs:
    ball_count: 2
    ball_count_type: total
    # No shoot again for multi since you
    # can camp in the shooter lane
    shoot_again: 0
    # begin when new ball
    # is manually plunged
    start_events:
    - mode_multiball_started
    # setting these probably breaks 'shoot_again'
    # let's see if MPF auto-handles the drain...
    #disable_events:
    #  multiball_multi_bombs_ball_lost
    #stop_events:
    #  multiball_multi_bombs_ball_lost

sound_player:
  mode_multiball_started:
    multiball_sfx:
      action: play
    multiball_bgm:
      action: play
    base_bgm:
      action: stop
  mode_multiball_stopped:
    multiball_bgm:
      action: stop
    base_bgm:
      action: play

show_player:
  mode_multiball_started:
    bumper_flash:
      action: play

light_player:
  mode_multiball_started:
    l_spinner: white
  mode_multiball_stopped:
    l_spinner: 000000

variable_player:
  s_bumper_1_active:
    score: 1000|block # bumpers 10x all day during multi
    multiball_score: 1000
  s_bumper_2_active:
    score: 1000|block
    multiball_score: 1000
  s_bumper_3_active:
    score: 1000|block
    multiball_score: 1000
  s_kicker_gun_active:
    score: 10000|block
    multiball_score: 10000
  s_slingshot_1_active:
    score: 20|block
    multiball_score: 20
  s_slingshot_2_active:
    score: 20|block
    multiball_score: 20
  s_spinner_active:
    score: 1000|block
    multiball_score: 1000
  s_rollover_bonus_ball_1_active:
    score: 2000|block
    multiball_score: 2000
  s_rollover_bonus_ball_2_active:
    score: 2000|block
    multiball_score: 2000
  s_rollover_advance_hole_1_active:
    score: 2000|block
    multiball_score: 2000
  s_rollover_advance_hole_2_active:
    score: 2000|block
    multiball_score: 2000
  s_stationary_thousand_active:
    score: 2000|block
    multiball_score: 2000
  s_stationary_special_active:
    score: 1000|block
    multiball_score: 1000
  s_drop_target_active:
    score: 2000|block
    multiball_score: 2000
  s_drop_target_behind_active:
    score: 1000|block
    multiball_score: 1000
  s_stationary_advance_bonus_active:
    score: 200|block
    multiball_score: 200
  s_stationary_advance_hole_score_active:
    score: 200|block
    multiball_score: 200
