#config_version=4
# actived when all 5 drop targets have dropped
# user wants to continue hitting those
# hitting the special kills the mode
mode:
  start_events: ball_hold_gun_multi_full
  priority: 121
  code: multiball.Custom
  stop_events: multiball_multi_bombs_ball_lost

scoring:
  s_kicker_gun_active:
    # score occurs when leaving lock
    # and anytime thereafter during multiball
    # THIS MAY CAUSE A DUPLICATE COIL FIRE...
    score: 10000|block
  s_bumper_1_active:
    score: 1000|block # bumpers 10x all day during multi
  s_bumper_2_active:
    score: 1000|block
  s_bumper_3_active:
    score: 1000|block

multiballs:
  multi_bombs:
    ball_count: 2
    ball_count_type: total
    # if ball drains within 15 seconds
    # player should get another one
    shoot_again: 15s
    # begin when new ball
    # is manually plunged
    start_events:
      mode_multiball_started
    # setting these probably breaks 'shoot_again'
    # let's see if MPF auto-handles the drain...
    #disable_events:
    #  multiball_multi_bombs_ball_lost
    #stop_events:
    #  multiball_multi_bombs_ball_lost
