#config_version=4
# this is just for adding the timer to the gun ball capture
# and preventing coil fire when ball rolls back over the switch
mode:
  start_events:
    s_kicker_gun_active
  priority: 110
  code: gun.Custom
  stop_events:
    in_and_out_of_gun

ball_holds:
  gun_hold:
    balls_to_hold: 1
    hold_devices: bd_gun
    release_one_events:
      timer_gun_timer_complete

timers:
  gun_timer:
    direction: up
    # restarts but doesn't stop!!!
    restart_on_complete: true
    start_value: 0
    end_value: 2
    control_events:
      - event: ball_hold_gun_hold_full
        action: reset
      - event: ball_hold_gun_hold_full
        action: start
      - event: timer_gun_timer_complete
        action: stop

# scoring happens via counter logic block in base mode
