#config_version=4
hardware:
  platform: smart_virtual
  rgb_dmd: smartmatrix

virtual_platform_start_active_switches:
  s_trough_1
  s_trough_2

smartmatrix:
  port: /dev/serial/by-id/usb-Teensyduino_USB_Serial_1519290-if00
  baud: 2500000
  old_cookie: true

physical_rgb_dmds:
  ppp_dmd::
    platform: smartmatrix
    brightness: 0.6
    gamma: 2.0
    fps: 24
