#config_version=4
ball_saves:
  default:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_trough_ball_eject_success
    # defaults true but only valid with auto-plunger
    auto_launch: false
    balls_to_save: 1
    debug: yes
