#config_version=4
# For external control / debugging
keyboard:
  # Left Flipper
  z:
    switch: s_flipper_1
  # Right Flipper
  "/":
    switch: s_flipper_2
  # Start Button
  s:
    switch: s_start
  # hit a switch (make the playfield active)
  l:
    switch: s_rollover_top_1
  1:
    switch: s_trough_1
    toggle: true
  2:
    switch: s_trough_2
    toggle: true
  3:
    switch: s_trough_jam
    toggle: true
  d:
    switch: s_drop_target
  g:
    switch: s_kicker_gun
