#config_version=4
modes:
  # dont need attract here (built-in)
  - initialize
  - base
  - cluster_bombs_a
  - cluster_bombs_b
  - flash_score
  - bombs_dropped
  - multiball
  - hole_score
  - explosion_bonus
  - explosion_multiplier
  - high_score
  - tilt
