#config_version=5
# Most "players" should be defined in modes.
# Only put exceptions here.
slide_player:
  init_done:
    default_slide:
      target: window
  # here because initialize mode ends before this
  # game_over or high_score modes begin...
  mode_game_over_started:
    awaiting_player_slide:
      action: play
      target: player_up_display
  mode_high_score_started:
    awaiting_player_slide:
      action: play
      target: player_up_display

sound_player:
  # must be here due to mode_end_action seemingly not able to "bubble up"
  # meaning, only be defined in the sound_player for game_over so music
  # doesn't restart if setting high score
  mode_high_score_started:
    high_score_bgm:
      action: play
  # carry song through both modes
  mode_game_over_stopped:
    high_score_bgm:
      action: stop
  balldevice_bd_missile_ball_entered: missile_collect_sfx

show_player:
  ball_ending{current_player.extra_balls>0}:
    shoot_again_dmd:
      loops: 0
  ball_save_default_saving_ball:
    shoot_again_dmd:
      loops: 0
