#config_version=4
slides:
# only using slides for the fake DMD currently, see players.yaml
  default_slide:
    widgets:
      - type: image
        image: backglass
        z: 1
      - type: color_dmd
        # source_display: dmd (default)
        width: 1024
        height: 256
        y: top-85%
        z: 2
  loading_slide:
    widgets:
      - type: text
        text: Loading...
        z: 0
