#config_version=5
slides:
# see players.yaml for slide changes per events
  default_slide:
    widgets:
      #  *********************************
      #  ****** BEGIN FAKE DMD *********** // uncomment fake DMD on Dev
      #  *********************************
      - type: display
        effects:
          - type: color_dmd
            dots_x: 128
            dots_y: 32
          # source_display: dmd (default)
        width: 1024
        height: 256
        y: top-85%
      #  *********************************
      #  ****** END FAKE DMD *************
      #  *********************************
      # this is the top of the LCD where the player
      # scores are for changing the "player up" assets
      - type: display
        width: 1920
        height: 324
        x: 0
        y: 0
        anchor_y: top
        anchor_x: left
        source_display: player_up_display
      # default backglass
      - type: image
        image: attract
  attract_post_slide:
    widgets:
      - type: image
        image: attract-post
  loading_slide:
    widgets:
      - type: text
        text: Loading...
        z: 0
  single_player_up_slide:
    widgets:
      - type: image
        image: backglass-single-player
        anchor_y: top
        y: top
  player_1_up_slide:
    widgets:
      - type: image
        image: backglass-player1-up
        anchor_y: top
        y: top
  player_2_up_slide:
    widgets:
      - type: image
        image: backglass-player2-up
        anchor_y: top
        y: top
  awaiting_player_slide:
    widgets:
      - type: image
        image: backglass-awaiting-player
        anchor_y: top
        y: top
