#config_version=4
widgets:
  player_1_up:
    - type: image
      image: backglass-player1-up
  player_2_up:
    - type: image
      image: backglass-player2-up
  player_up:
    - type: text
      text: "Player (number) Up"
      # water blue from backglass
      color: 99CCFF
      style: dmd_small
  ball_count:
    - type: text
      text: "Ball: (ball)"
      # water blue from backglass
      color: FF6242
      style: dmd_small
  current_score:
    - type: text
      text: "(score)"
      number_grouping: true # adds commas to integer value display
      min_digits: 2
      color: F9ED32
      style: dmd_big
      font_size: 12
      animations:
        add_to_slide: pulsate_fast
  player_one_score:
    - type: text
      text: "(player1|score)"
      number_grouping: true # adds commas to integer value display
      min_digits: 2
      color: 333333
      font_size: 110
      anchor_x: right
      y: top-20.5%
      x: center-10%
  player_two_score:
    - type: text
      text: "(player2|score)"
      number_grouping: true
      min_digits: 2
      color: 333333
      font_size: 110
      anchor_x: right
      y: top-20.5% # 18 + 2+2 margin
      x: right-6%
  shoot_again:
    - type: text
      text: "PLAYER (number) SHOOT AGAIN"
      style: dmd_small
      color: FF6242
      anchor_y: top
      y: top-4%
      animations:
        add_to_slide: pulsate_slow
  credits_music:
    - type: text
      text: "Music by Josiah Cox, Ryan Richardson, Terence Klein & Elliot Starks"
      style: dmd_small
      color: 99CCFF
      x: 512
      animations:
        add_to_slide: scroll_left_long
  credits_sfx:
    - type: text
      text: "Sound Effects by Raphael Rodriguez"
      style: dmd_small
      color: 99CCFF
      x: 256
      animations:
        add_to_slide: scroll_left_medium
  credits_game:
    - type: text
      text: "Zaccaria Combat reimagined by Pinball Plaid - Steve Prehoda, Josiah Cox & Ryan Richardson"
      style: dmd_small
      color: 99CCFF
      x: 512
      animations:
        add_to_slide: scroll_left_long
  credits_podcast:
    - type: text
      text: "Subscribe to the Pinball Plaid Podcast from http://pinballplaid.com/show"
      style: dmd_small
      color: 99CCFF
      x: 512
      animations:
        add_to_slide: scroll_left_long
  high_score_1:
    - type: text
      text: "(machine|score1_label) (machine|score1_name): (machine|score1_value)"
      number_grouping: true
      min_digits: 2
      style: dmd_small
      color: F9ED32
      x: 256
      animations:
        add_to_slide: scroll_left
  high_score_2:
    - type: text
      text: "1st) (machine|score2_name): (machine|score2_value)"
      number_grouping: true
      min_digits: 2
      style: dmd_small
      color: F9ED32
      x: 256
      animations:
        add_to_slide: scroll_left
  high_score_3:
    - type: text
      text: "2nd) (machine|score3_name): (machine|score3_value)"
      number_grouping: true
      min_digits: 2
      style: dmd_small
      color: F9ED32
      x: 256
      animations:
        add_to_slide: scroll_left
  high_score_4:
    - type: text
      text: "3rd) (machine|score4_name): (machine|score4_value)"
      number_grouping: true
      min_digits: 2
      style: dmd_small
      color: F9ED32
      x: 256
      animations:
        add_to_slide: scroll_left
  high_score_5:
    - type: text
      text: "4th) (machine|score5_name): (machine|score5_value)"
      number_grouping: true
      min_digits: 2
      style: dmd_small
      color: F9ED32
      x: 256
      animations:
        add_to_slide: scroll_left
  title:
    - type: text
      text: "Zaccaria “Combat”"
      style: dmd_big
      color: FF6242
      x: -128
      animations:
        add_to_slide: scroll_right
  credit:
    - type: text
      text: "Reimagined by:"
      style: dmd_small
      color: F9ED32
      font_size: 9
  company:
    - type: text
      text: "Pinball Plaid"
      color: 99CCFF
      style: dmd_med
      animations:
        add_to_slide: pulsate_slow
  game_over:
    - type: text
      text: "GAME OVER"
      style: dmd_big
      color: FF6242
      animations:
        add_to_slide: pulsate_slow
