#config_version=4
widgets:
  player_1_up:
    - type: image
      image: backglass-player1-up
  player_2_up:
    - type: image
      image: backglass-player2-up
  player_up:
    - type: text
      text: "Player (number) Up"
      # water blue from backglass
      color: 99CCFF
      style: dmd_small
  ball_count:
    - type: text
      text: "Ball: (ball)"
      # water blue from backglass
      color: 99CCFF
      style: dmd_small
  current_score:
    - type: text
      text: "(score)"
      number_grouping: true # adds commas to integer value display
      min_digits: 2
      color: F9ED32
      style: dmd_big
      font_size: 12
      animations:
        add_to_slide: pulsate
  player_one_score:
    - type: text
      text: "(machine|player1_score)"
      number_grouping: true # adds commas to integer value display
      min_digits: 2
      color: 333333
      font_size: 110
      anchor_x: right
      y: top-20.5%
      x: center-10%
  player_two_score:
    - type: text
      text: "(machine|player2_score)"
      number_grouping: true
      min_digits: 2
      color: 333333
      font_size: 110
      anchor_x: right
      y: top-20.5% # 18 + 2+2 margin
      x: right-6%
  title:
    - type: text
      text: "Zaccaria “Combat”"
      style: dmd_big
      color: F9ED32
      animations:
        add_to_slide: scroll_right
  credit:
    - type: text
      text: "Reimagined by:"
      style: dmd_small
      color: F9ED32
      font_size: 9
      animations:
        add_to_slide: pulsate
  company:
    - type: text
      text: "Pinball Plaid"
      color: F9ED32
      style: dmd_med
      animations:
        add_to_slide: pulsate
