#config_version=4
config:
- devices/controller.yaml
- devices/displays.yaml
- devices/ball_devices.yaml
- devices/switches.yaml
- devices/coils.yaml
- devices/leds.yaml
- devices/ball_devices.yaml
- animations.yaml
- widgets.yaml
- slides.yaml
- sounds.yaml
- players/slide_player.yaml
- players/widget_player.yaml
- players/show_player.yaml
- modes.yaml
- keyboard.yaml
