#config_version=4
config:
- devices/controller.yaml
- devices/displays.yaml
- devices/switches.yaml
- devices/coils.yaml
- devices/ball_devices.yaml
- views/animations.yaml
- views/widgets.yaml
- views/slides.yaml
- views/players.yaml
- modes.yaml
- keyboard.yaml
