#config_version=4
hardware:
  platform: smart_virtual
# all switches left to right
switches:
  s_bumper_north_1:
    number:
  s_bumper_north_2:
    number:
  s_bumper_north_3:
    number:
  s_bumper_south_1:
    number:
  s_bumper_south_2:
    number:
  s_flipper_1:
    number:
  s_flipper_2:
    number:
  s_spinner_1:
    number:
  s_rollover_north_1:
    number:
  s_rollover_north_2:
    number:
  s_rollover_north_3:
    number:
  s_rollover_north_4:
    number:
  s_rollover_north_5:
    number:
  s_rollover_north_6:
    number:
  s_rollover_north_7:
    number:
  s_rollover_south_1:
    number:
  s_rollover_south_2:
    number:
  s_rollover_south_3:
    number:
  s_rollover_south_4:
    number:
  s_stationary_northwest:
    number:
  s_stationary_special:
    number:
  s_stationary_bombs_1:
    number:
  s_stationary_bombs_2:
    number:
  s_stationary_bombs_3:
    number:
  s_stationary_bombs_4:
    number:
  s_stationary_bombs_5:
    number:
  s_stationary_southeast_1:
    number:
  s_stationary_southeast_2:
    number:
