#config_version=4
hardware:
    platform: smart_virtual

switches:
  s_bumper_1_left:
    number:
  s_bumper_2_center:
    number:
  s_bumper_3_right:
    number:
  s_flipper_1_left:
    number:
  s_flipper_2_right:
    number:
  s_spinner_1:
    number:
  s_rollover_north_1:
    number:
  s_rollover_north_2:
    number:
  s_rollover_north_3:
    number:
  s_rollover_north_4:
    number:
  s_rollover_north_5:
    number:
  s_rollover_north_6:
    number:
  s_rollover_north_7:
    number:
