#config_version=6
#######################
## PRODUCTION CONFIG ##
#######################
config:
- common/assets.yaml
- common/devices/displays.yaml
- production/fast.yaml
- production/hardware.yaml
- production/window.yaml
- common/devices/flippers.yaml
- common/devices/ball_devices.yaml
- common/devices/switches.yaml
- common/devices/coils.yaml
- common/devices/autofire_coils.yaml
- common/devices/leds.yaml
- common/devices/ball_devices.yaml
- common/playfields.yaml
- common/ball_saves.yaml
- common/game.yaml
- common/shots.yaml
- common/animations.yaml
- common/widgets.yaml
- common/slides.yaml
- common/sounds.yaml
- common/players.yaml
- common/queue_relay.yaml
- common/modes.yaml
- common/keyboard.yaml
