#config_version=4
#######################
## PRODUCTION CONFIG ##
#######################
config:
- global/devices/displays.yaml
- production/controller.yaml
- production/window.yaml
- global/devices/ball_devices.yaml
- global/devices/switches.yaml
- global/devices/coils.yaml
- global/devices/leds.yaml
- global/devices/ball_devices.yaml
- global/game.yaml
- global/animations.yaml
- global/widgets.yaml
- global/slides.yaml
- global/sounds.yaml
- global/players/slide_player.yaml
- global/players/widget_player.yaml
- global/players/show_player.yaml
- global/modes.yaml
- global/keyboard.yaml
