#config_version=4
#######################
## PRODUCTION CONFIG ##
#######################
config:
- global/assets.yaml
- global/devices/displays.yaml
- production/controller.yaml
- production/display.yaml
- global/devices/flippers.yaml
- global/devices/ball_devices.yaml
- global/devices/switches.yaml
- global/devices/coils.yaml
- global/devices/autofire_coils.yaml
- global/devices/leds.yaml
- global/devices/ball_devices.yaml
- global/ball_saves.yaml
- global/game.yaml
- global/shots.yaml
- global/animations.yaml
- global/widgets.yaml
- global/slides.yaml
- global/sounds.yaml
- global/players/slide_player.yaml
- global/players/widget_player.yaml
- global/players/show_player.yaml
- global/players/sound_player.yaml
- global/queue_relay.yaml
- global/modes.yaml
- global/keyboard.yaml
