#config_version=4
slides:
# only using slides for the fake DMD currently, see players.yaml
  dmd_slide:
    - type: color_dmd
      width: 1024
      height: 256
      y: top-85%
#  # Start button has been pressed
#  started:
#    widgets:
#      # show temp virtual DMD bottom-center
#      background
#  # Game is loading up
#  loading:
#    widgets:
#      - type: text
#        text: Loading...
