#config_version=4
hardware:
  platform: fast
  driverboards: fast
  rgb_dmd: smartmatrix

fast:
  watchdog: 5000
  ports:
    # A = DMD /dev/tty.usbserial-142A
    # B = MAIN
    # C = RBG LED
    # D = Custom (unused)
    /dev/ttyUSB1
    /dev/ttyUSB2

smartmatrix:
  port: /dev/ttyACM0
  baud: 2500000
  old_cookie: true

physical_rgb_dmds:
  ppp_dmd::
    platform: smartmatrix
    brightness: 0.6
    gamma: 2.0
    fps: 24
