#config_version=5
hardware:
  platform: fast
  driverboards: fast
  rgb_dmd: smartmatrix

fast:
  watchdog: 5000
  hardware_led_fade_time: 65ms
  rgb_buffer: 10
  ports:
    # A = DMD (not on the Nano)
    # B = MAIN
    # C = RBG LED
    # D = Custom (unused and also not on the Nano)
    /dev/ttyUSB1
    /dev/ttyUSB2

smartmatrix:
  smartmatrix_1:
    port: /dev/ttyACM0
    baud: 3400000

rgb_dmds:
  smartmatrix_1:
    hardware_brightness: 0.5
