#config_version=6

# Boards
# FP-CPU-003 (Nano)
# FP-I/O-3208
# FP-I/O-1616
# FP-I/O-0804
fast:
  net:
    port: auto
    controller: nano
    io_loop:
      # nano and ____ in backbox
      "bb0804": # (old-number: 2)
        model: FP-I/O-3208
        # short black cable from nano
        order: 1
      # io boards 3280 and 0804 under playfield
      "pf3208": # trough (old-number: 0)
        model: FP-I/O-3208
        # white cable from bb0804
        order: 2
      "pf0804": # left-side slingshot (old-number: 1)
        model: FP-I/O-0804
        # short black cable from pf3208
        order: 3
  rgb:
    port: auto


  # legacy config (mpf 0.56 and lower):
  #  watchdog: 5000
  #  hardware_led_fade_time: 65ms
  #  rgb_buffer: 3
  #  ports:
  #    # A = DMD (not on the Nano)
  #    # B = MAIN
  #    # C = RBG LED
  #    # D = Custom (unused and also not on the Nano)
  #  - /dev/ttyUSB1
  #  - /dev/ttyUSB2
