#config_version=4
physical_rgb_dmd:
  brightness: 0.6
  gamma: 2.0
  fps: 24
window:
  width: 1920
  height: 1080
  title: Immortal Combat
  resizable: false
  fullscreen: true
  borderless: true
  exit_on_escape: true
  source_display: window
