#config_version=4
sound_player:
  mode_attract_started:
    attract_bgm:
      action: play
  mode_base_started:
    attract_bgm:
      action: stop
    plunging_bgm:
      action: play
  balldevice_playfield_ball_enter:
    plunging_bgm:
      action: stop
