#config_version=6
mode:
  start_events: ball_starting
  priority: 100
  code: initialize.Custom

timers:
  start_base:
    start_value: 0
    end_value: 1
    direction: up
    start_running: true
    # we don't need a full second between
    tick_interval: 500ms
    control_events:
    - event: timer_start_base_complete
      action: stop

ball_holds:
  missile_hold:
    enable_events: ball_starting
    balls_to_hold: 1
    hold_devices: bd_missile
    release_one_events:
      s_kicker_missile_active: 1s
  gun_hold:
    balls_to_hold: 1
    hold_devices: bd_gun
    enable_events:
    - mode_bombs_dropped_stopped
    - mode_base_started
    disable_events:
    # laser bombs has own hold to multiball
    - mode_bombs_dropped_started
    release_one_events:
      ball_hold_gun_hold_full: 1s

# blocks reset on completion by default
counters:
  spins:
    count_events: s_spinner_active
    starting_count: 0
    count_complete_value: 5
    direction: up
    events_when_complete: spins_advances_hole
    restart_events: spins_advances_hole
  hole_score:
    restart_events:
    - ball_starting
    - mode_hole_score_will_stop
    # - ball_hold_middle_hold_balls_released
    count_events:
    - s_rollover_advance_hole_1_active
    - s_rollover_advance_hole_2_active
    - s_stationary_advance_hole_score_active
    - spins_advances_hole
    # control_events:
    # - event: s_kicker_missile_inactive
    #   action: jump
    #   value: 0
    starting_count: 0
    count_complete_value: 10
    events_when_complete: hole_score_complete
    direction: up
    # should stay at 10 until it's collected
    reset_on_complete: false
    disable_on_complete: false
  explosion_bonus:
    persist_state: true
    restart_events: mode_base_started
    count_events:
    - s_stationary_advance_bonus_active
    - cluster_a_advance_bonus_hit
    - cluster_b_advance_bonus_hit
    # need to start at 1 to sync the led show
    # GOTCHA - 2 == 1000 and 3 == 2000
    starting_count: 1
    count_complete_value: 11
    events_when_complete: explosion_bonus_complete
    direction: up
    reset_on_complete: false

extra_balls:
  score_level_1:
    label: 'Score Level 1'

# DMD Stuff
widget_player:
  mode_base_started:
    current_score:
      action: add
    player_up:
      action: add
    p1_score:
      action: add
    p2_score:
      action: add
    p3_score:
      action: add
    p4_score:
      action: add
    ball_count:
      action: add
    title:
      action: remove
    credit:
      action: remove
    company:
      action: remove
  ball_save_default_saving_ball:
    shoot_again:
      action: add
  s_shooter_lane_inactive:
    shoot_again:
      action: remove
  playfield_active:
    shoot_again:
      action: remove

show_player:
  logicblock_explosion_bonus_updated:
    explosion_bonus_advance:
      start_step: current_player.explosion_bonus_state.value
  mode_base_started:
    hole_score_collect:
      action: play
  ball_save_default_timer_start:
    shoot_again_normal:
      action: play
  ball_save_default_hurry_up:
    shoot_again_normal:
      action: stop
    shoot_again_hurry:
      action: play
      loops: 0
  ball_save_default_disabled:
    shoot_again_normal:
      action: stop
    shoot_again_hurry:
      action: stop

variable_player:
  logicblock_hole_score_updated:
    hole_score_count:
      action: set
      int: value
  mode_hole_score_stopped:
    hole_score_count:
      action: set
      int: 0

light_player:
  mode_initialize_started:
    tag_hole_score: '000000'
  mode_hole_score_stopped:
    tag_hole_score: '000000'
  player_hole_score_count{current_player.hole_score_count == 0}:
    tag_hole_score: '000000'
  player_hole_score_count{current_player.hole_score_count == 1}:
    l_hole_score_lane_1: '56A20A'
  player_hole_score_count{current_player.hole_score_count == 2}:
    l_hole_score_lane_1: '56A20A'
    l_hole_score_lane_2: '56A20A'
  player_hole_score_count{current_player.hole_score_count == 3}:
    l_hole_score_lane_1: '56A20A'
    l_hole_score_lane_2: '56A20A'
    l_hole_score_lane_3: '56A20A'
  player_hole_score_count{current_player.hole_score_count == 4}:
    l_hole_score_lane_1: '56A20A'
    l_hole_score_lane_2: '56A20A'
    l_hole_score_lane_3: '56A20A'
    l_hole_score_lane_4: 'FF69B4'
  player_hole_score_count{current_player.hole_score_count == 5}:
    l_hole_score_lane_1: '56A20A'
    l_hole_score_lane_2: '56A20A'
    l_hole_score_lane_3: '56A20A'
    l_hole_score_lane_4: 'FF69B4'
    l_hole_score_lane_5: 'FF69B4'
  player_hole_score_count{current_player.hole_score_count == 6}:
    l_hole_score_lane_1: '56A20A'
    l_hole_score_lane_2: '56A20A'
    l_hole_score_lane_3: '56A20A'
    l_hole_score_lane_4: 'FF69B4'
    l_hole_score_lane_5: 'FF69B4'
    l_hole_score_lane_6: 'FF69B4'
  player_hole_score_count{current_player.hole_score_count == 7}:
    l_hole_score_lane_1: '56A20A'
    l_hole_score_lane_2: '56A20A'
    l_hole_score_lane_3: '56A20A'
    l_hole_score_lane_4: 'FF69B4'
    l_hole_score_lane_5: 'FF69B4'
    l_hole_score_lane_6: 'FF69B4'
    l_hole_score_lane_7: 'FFFF00'
  player_hole_score_count{current_player.hole_score_count == 8}:
    l_hole_score_lane_1: '56A20A'
    l_hole_score_lane_2: '56A20A'
    l_hole_score_lane_3: '56A20A'
    l_hole_score_lane_4: 'FF69B4'
    l_hole_score_lane_5: 'FF69B4'
    l_hole_score_lane_6: 'FF69B4'
    l_hole_score_lane_7: 'FFFF00'
    l_hole_score_lane_8: 'FFFF00'
  player_hole_score_count{current_player.hole_score_count == 9}:
    l_hole_score_lane_1: '56A20A'
    l_hole_score_lane_2: '56A20A'
    l_hole_score_lane_3: '56A20A'
    l_hole_score_lane_4: 'FF69B4'
    l_hole_score_lane_5: 'FF69B4'
    l_hole_score_lane_6: 'FF69B4'
    l_hole_score_lane_7: 'FFFF00'
    l_hole_score_lane_8: 'FFFF00'
    l_hole_score_lane_9: 'FFFF00'
  player_hole_score_count{current_player.hole_score_count == 10}:
    l_hole_score_lane_1: '56A20A'
    l_hole_score_lane_2: '56A20A'
    l_hole_score_lane_3: '56A20A'
    l_hole_score_lane_4: 'FF69B4'
    l_hole_score_lane_5: 'FF69B4'
    l_hole_score_lane_6: 'FF69B4'
    l_hole_score_lane_7: 'FFFF00'
    l_hole_score_lane_8: 'FFFF00'
    l_hole_score_lane_9: 'FFFF00'
    l_hole_score_lane_10: 'FF8000'
