#config_version=6
mode:
  start_events: ball_starting
  priority: 100
  code: initialize.Custom

timers:
  start_base:
    start_value: 0
    end_value: 1
    direction: up
    start_running: true
    # we don't need a full second between
    tick_interval: 500ms
    control_events:
    - event: timer_start_base_complete
      action: stop

ball_holds:
  missile_hold:
    enable_events: ball_starting
    balls_to_hold: 1
    hold_devices: bd_missile
    release_one_events:
      s_kicker_missile_active: 1s
  gun_hold:
    balls_to_hold: 1
    hold_devices: bd_gun
    enable_events:
    - mode_bombs_dropped_stopped
    - mode_base_started
    disable_events:
    # laser bombs has own hold to multiball
    - mode_bombs_dropped_started
    release_one_events:
      ball_hold_gun_hold_full: 1s

# blocks reset on completion by default
counters:
  spins:
    count_events: s_spinner_active
    starting_count: 0
    count_complete_value: 5
    direction: up
    events_when_complete: spins_advances_hole
    restart_events: spins_advances_hole
  hole_score:
    persist_state: true
    # GOTCHA: will not persist player variable AT ALL
    # without this set... so we always reset on base mode start
    restart_events:
    - mode_base_started
    - mode_hole_score_stopped
    count_events:
    - s_rollover_advance_hole_1_active
    - s_rollover_advance_hole_2_active
    - s_stationary_advance_hole_score_active
    - spins_advances_hole
    starting_count: 1
    count_complete_value: 10
    events_when_complete: hole_score_complete
    direction: up
    reset_on_complete: false
  explosion_bonus:
    persist_state: true
    restart_events: mode_base_started
    count_events:
    - s_stationary_advance_bonus_active
    - cluster_a_advance_bonus_hit
    - cluster_b_advance_bonus_hit
    # need to start at 1 to sync the led show
    # GOTCHA - 2 == 1000 and 3 == 2000
    starting_count: 1
    count_complete_value: 11
    events_when_complete: explosion_bonus_complete
    direction: up
    reset_on_complete: false

extra_balls:
  score_level_1:
    label: 'Score Level 1'

# DMD Stuff
widget_player:
  mode_base_started:
    current_score:
      action: add
    player_up:
      action: add
    p1_score:
      action: add
    p2_score:
      action: add
    p3_score:
      action: add
    p4_score:
      action: add
    ball_count:
      action: add
    title:
      action: remove
    credit:
      action: remove
    company:
      action: remove
  ball_save_default_saving_ball:
    shoot_again:
      action: add
  playfield_active:
    shoot_again:
      action: remove

show_player:
  logicblock_explosion_bonus_updated:
    explosion_bonus_advance:
      start_step: current_player.explosion_bonus_state.value
  logicblock_hole_score_updated:
    hole_score_advance:
      start_step: current_player.hole_score_state.value
  # TODO - and remove this after moving collect show
  mode_base_started:
    hole_score_collect:
      action: play
  ball_save_default_timer_start:
    shoot_again_normal:
      action: play
  ball_save_default_hurry_up:
    shoot_again_normal:
      action: stop
    shoot_again_hurry:
      action: play
      loops: 0
  ball_save_default_disabled:
    shoot_again_normal:
      action: stop
    shoot_again_hurry:
      action: stop
