#config_version=4
mode:
  start_events:
    mode_cluster_bombs_a_stopped
  stop_events:
    timer_cluster_b_complete
    s_bumper_1_active
    s_bumper_2_active
    s_bumper_3_active
  priority: 150

timers:
  cluster_b:
    start_value: 0
    end_value: 8
    direction: up
    control_events:
      - event: mode_cluster_bombs_b_started
        action: reset
      - event: mode_cluster_bombs_b_started
        action: start
      - event: timer_cluster_b_complete
        action: stop

led_player:
  mode_cluster_bombs_b_started:
    l_rollover_top_2: ff8000
    l_rollover_top_3: ff8000
    l_rollover_top_5: ff8000
    l_rollover_top_6: ff8000
  timer_cluster_b_complete:
    l_rollover_top_2: 000000
    l_rollover_top_3: 000000
    l_rollover_top_5: 000000
    l_rollover_top_6: 000000

scoring:
  s_rollover_top_2_active:
    score: 5000|block
  s_rollover_top_3_active:
    score: 5000|block
  s_rollover_top_5_active:
    score: 5000|block
  s_rollover_top_6_active:
    score: 5000|block
