#config_version=4
mode:
  start_events:
    mode_cluster_bombs_a_stopped
  stop_events:
    timer_cluster_b_complete
    s_bumper_1_active
    s_bumper_2_active
    s_bumper_3_active
    ball_will_end
    ball_starting
    game_ended
  priority: 150

timers:
  cluster_b:
    start_value: 0
    end_value: 8
    direction: up
    control_events:
      - event: mode_cluster_bombs_b_started
        action: reset
      - event: mode_cluster_bombs_b_started
        action: start
      - event: timer_cluster_b_complete
        action: stop
      - event: ball_will_end
        action: stop

shots:
  cluster_b_advance_bonus:
    switches:
      s_rollover_top_2
      s_rollover_top_3
      s_rollover_top_5
      s_rollover_top_6

# opposite cluster's sounds
sound_player:
  s_rollover_top_1_active: gun_shot_near_sfx
  s_rollover_top_4_active: gun_shot_near_sfx
  s_rollover_top_7_active: gun_shot_near_sfx

led_player:
  mode_cluster_bombs_b_started:
    l_rollover_top_2: ff8000
    l_rollover_top_3: ff8000
    l_rollover_top_5: ff8000
    l_rollover_top_6: ff8000
  timer_cluster_b_complete:
    l_rollover_top_2: 000000
    l_rollover_top_3: 000000
    l_rollover_top_5: 000000
    l_rollover_top_6: 000000

scoring:
  s_rollover_top_2_active:
    score: 5000|block
  s_rollover_top_3_active:
    score: 5000|block
  s_rollover_top_5_active:
    score: 5000|block
  s_rollover_top_6_active:
    score: 5000|block
