#config_version=6
animations:
  scroll_right:
    - property: x
      value: -128
      duration: 1ms
    - property: x
      value: 196
      duration: 4s
      repeat: true
  scroll_left:
    - property: x
      value: 128
      duration: 1ms
    - property: x
      value: -128
      duration: 4s
      repeat: true
  scroll_left_medium:
    - property: x
      value: 256
      duration: 1ms
    - property: x
      value: -256
      duration: 8s
      repeat: true
  scroll_left_long:
    - property: x
      value: 448
      duration: 1ms
    - property: x
      value: -448
      duration: 12s
      repeat: true
  pulsate_fast:
    - property: opacity
      value: 0.0
      duration: 250ms
    - property: opacity
      value: 1.0
      duration: 250ms
      repeat: true
  pulsate_slow:
    - property: opacity
      value: 0.0
      duration: 500ms
    - property: opacity
      value: 1.0
      duration: 500ms
      repeat: true
