#config_version=6
# For external control / debugging
#
# Press p->d to simulate beginning play
# (plunge -> switch hit)
#
# To expire ball save, press 1
# (trough drain) then p->d again
keyboard:
  # Left Flipper
  z:
    switch: s_flipper_1
  # Right Flipper
  "/":
    switch: s_flipper_2
  # Start Button
  s:
    switch: s_start
  # hit a switch (make the playfield active)
  l:
    switch: s_rollover_top_1
  1:
    switch: s_trough_1
    toggle: true
    # event: ball_drain
    # params:
    #   balls: 1
    #   device: s_trough_1
  2:
    switch: s_trough_2
    toggle: true
  3:
    switch: s_trough_jam
    toggle: true
  p:
    switch: s_shooter_lane
  a:
    switch: s_stationary_advance_bonus
  d:
    switch: s_drop_target
  g:
    switch: s_kicker_gun
  m:
    switch: s_kicker_missile
  h:
    switch: s_stationary_advance_hole_score
  b:
    switch: s_bumper_1
  c:
    switch: s_stationary_special
  n:
    switch: s_spinner
  t:
    switch: s_tilt
  q:
    event: start_high_score
  o:
    event: start_game_over
