#config_version=6

slides:
  # see players.yaml for slide changes per events
  default_slide:
    widgets:
      #  ****** BEGIN FAKE DMD ***********
      - type: display
        effects:
          - type: color_dmd
            dot_filter: false
            gain: 1.1
            blur: 0.2
        width: 1920
        height: 720
      #  ****** END FAKE DMD *************
  loading_slide:
    widgets:
      - type: text
        text: Loading...
        z: 0
