#config_version=6

# Most "players" should be defined in modes.
# Only put exceptions here.
slide_player:
  init_done:
    default_slide:
      target: window
  # here because initialize mode ends before this
  # game_over or high_score modes begin...
  # mode_game_over_started:
  #   awaiting_player_slide:
  #     action: play
  #     target: player_up_display
  # mode_high_score_started:
  #   awaiting_player_slide:
  #     action: play
  #     target: player_up_display
