#config_version=6

sound_player:
  mode_game_started: gun_explosion_sfx
  # only good enough for 2 players
  multiplayer_game: bullet_ping_pool
  # must be here due to mode_end_action seemingly not able to "bubble up"
  # meaning, only be defined in the sound_player for game_over so music
  # doesn't restart if setting high score
  mode_high_score_started:
    high_score_bgm:
      action: play
  # carry song through both modes
  mode_game_over_stopped:
    high_score_bgm:
      action: stop
  balldevice_bd_missile_ball_entered: missile_collect_sfx
