#config_version=6

player_vars:
  score_level:
    initial_value: 0
  hole_score_count:
    initial_value: 0
  multiball_score:
    initial_value: 0

machine_vars:
  master_volume:
    initial_value: 0.9
