#config_version=4
widget_player:
  init_done:
    background:
      action: add
  mode_attract_started:
    title:
      action: add
      target: dmd
      widget_settings:
        anchor_y: top
        y: top-4%
    credit:
      action: add
      target: dmd
      widget_settings:
        anchor_y: top
        y: top-50%
    company:
      action: add
      target: dmd
      widget_settings:
        anchor_y: top
        y: top-74%
    background:
      action: add
      #target: window - actually breaks even though seems to be default
    current_score:
      action: remove # when a game ends...
    player_scores:
      action: remove
    player_up:
      action: remove
    ball_count:
      action: remove
  mode_base_started:
    current_score:
      action: add
      target: dmd
      widget_settings:
        anchor_y: top
        anchor_x: right
        y: top-4%
        x: right-1%
    player_scores:
      action: add
      target: dmd
    player_up:
      action: add
      target: dmd
      widget_settings:
        anchor_y: bottom
        anchor_x: right
        y: bottom+26%
        x: right-1%
    ball_count:
      action: add
      target: dmd
      widget_settings:
        anchor_y: bottom
        anchor_x: right
        y: bottom+4%
        x: right-1%
    background:
      action: add
    title:
      action: remove
    credit:
      action: remove
    company:
      action: remove

# Adds the virtual dmd, see slides.yaml
slide_player:
  mode_attract_started:
    ready:
      target: window
# init_done: loading
#  ball_started:
#    started:
#      target: window
