#config_version=4
slides:
#  # 'Attract mode (game loaded / not started)
  ready:
    - type: color_dmd
      width: 512
      height: 128
      y: top-85%
#  # Start button has been pressed
#  started:
#    widgets:
#      # show temp virtual DMD bottom-center
#      background
#  # Game is loading up
#  loading:
#    widgets:
#      - type: text
#        text: Loading...
