#config_version=4
slides:
  loading:
    widgets:
      - text: Loading...
        type: text
  ready:
    widgets:
      - type: text
        text: Ready to play
        font_size: 50
        color: red
        y: 80
      - type: text
        text: Combat by Zaccaria
        font_size: 50
        color: red
      - type: rectangle
        width: 480
        height: 100
  started:
    widgets:
      type: text
      text: PLAYER (number) BALL (ball)
slide_player:
  init_done: loading
  mode_attract_started: ready
  ball_started: started
