#config_version=4
widgets:
  background:
    - type: image
      image: backglass
  player_state:
    - type: text
      text: PLAYER (number) BALL (ball)
      color: F9ED32
      style: dmd_med
  title:
    - type: text
      text: Zaccaria “Combat”
      color: F9ED32
      style: dmd_big
      animations:
        add_to_slide: scroll_right
  credit:
    - type: text
      text: 'Reimagined by:'
      color: F9ED32
      style: dmd_small
      y: 25%
      anchor_y: top
      anchor_x: left
      animations:
        add_to_slide: pulsate
  company:
    - type: text
      y: 75%
      anchor_y: top
      anchor_x: left
      text: Pinball Plaid
      color: F9ED32
      style: dmd_small
      animations:
        add_to_slide: pulsate
