#config_version=4
# actived when all 5 drop targets have dropped
# user wants to continue hitting those
# hitting the special kills the mode
mode:
  start_events: bombs_complete # fired by BOTH logic block AND reset switch
  priority: 125
  code: bombs_dropped.Custom
  stop_events:
    s_stationary_special_active
    mode_multiball_stopped # after multi, you must hit drops again

sound_player:
  mode_bombs_dropped_started: laser_bombs_sfx

extra_balls:
  laser_bombs_outlanes:
    award_events:
      s_rollover_bonus_ball_1_active
      s_rollover_bonus_ball_2_active
    reset_events: extra_ball_awarded # infinite extra balls for now

led_player:
  mode_bombs_dropped_started:
    l_special: FF0000 # red
    l_bonus_ball_1: FF0000
    l_bonus_ball_2: FF0000
  s_rollover_bonus_ball_1_active:
    l_bonus_ball_1:
      color: 000000
    l_bonus_ball_2:
      color: 000000
  s_rollover_bonus_ball_2_active:
    l_bonus_ball_1:
      color: 000000
    l_bonus_ball_2:
      color: 000000

coil_player:
  # directly fire drop target coil instead
  # to reset the drops on exit (to prevent infinite loop)
  mode_bombs_dropped_stopped: c_drop_target
  # TODO: add a game sound, knocker reserved for "score levels"
  #extra_ball_awarded: c_knocker

# multiball_locks seems to release when multiball
# begins, but we still need the player to plunge
# workaround by "holding" until they hit a switch
ball_holds:
  gun_multi:
    balls_to_hold: 1
    hold_devices: bd_gun
    release_one_events:
      # release on any 'playfield_active' switch
      sw_playfield_active
    disable_events:
      # needs to not "hold" any further balls after multiball is
      # activated BUT still need to release the held ball when
      # during multiball
      mode_multiball_started
    enable_events:
      mode_bombs_dropped_started
      mode_multiball_stopped

scoring:
  s_stationary_special_active:
    score: 20000|block
  s_drop_target_active:
    score: 10000|block # in ask app, these were 5000
  s_kicker_gun_active:
    # activates multiball
    #   - no score when rolling into the lock
    #     only "out" of it after user launches
    #     next ball and it hits a top rollover
    score: 0|block

