#config_version=6
coils:
  c_trough_eject:
    number: pf3208-2
    default_pulse_ms: 40
    default_hold_power: 0.1
  c_flipper_main_1:
    number: pf3208-6
    default_pulse_ms: 27
    default_hold_power: 0.5
  c_flipper_hold_1:
    number: pf3208-7
    allow_enable: true
  c_flipper_main_2:
    number: pf3208-5
    default_pulse_ms: 27
    default_hold_power: 0.5
  c_flipper_hold_2:
    number: pf3208-4
    allow_enable: true
  c_bumper_1:
    number: pf0804-3
    default_pulse_ms: 40
    default_hold_power: 0.1
  c_bumper_2:
    number: pf0804-2
    default_pulse_ms: 40
    default_hold_power: 0.1
  c_bumper_3:
    number: pf0804-1
    default_pulse_ms: 40
    default_hold_power: 0.1
  c_slingshot_1:
    number: pf0804-0
    default_pulse_ms: 40
    default_hold_power: 0.1
  c_slingshot_2:
    number: bb0804-0
    default_pulse_ms: 40
    default_hold_power: 0.1
  c_kicker_missile:
    number: bb0804-2
    default_pulse_ms: 80
    default_hold_power: 0.1
  c_kicker_gun:
    number: pf3208-0
    default_pulse_ms: 60
    default_hold_power: 0.1
  c_knocker:
    number: bb0804-1
    default_pulse_ms: 40
    default_hold_power: 0.1
  c_drop_target:
    number: pf3208-1
    default_pulse_ms: 100
    default_hold_power: 0.1
