#config_version=6
lights:
  l_spinner:
    type: grb
    number: 1-15
  l_special:
    type: grb
    number: 1-16
  l_bonus_ball_1:
    type: grb
    number: 1-3
  l_bonus_ball_2:
    type: grb
    number: 1-4
  l_shoots_again:
    type: grb
    number: 1-2
  l_bonus_multiplier:
    type: grb
    number: 1-1
  l_bumper_1:
    type: grb
    number: 1-35
  l_bumper_2:
    type: grb
    number: 1-36
  l_bumper_3:
    type: grb
    number: 1-37
  l_missile:
    type: grb
    number: 1-34
  l_rollover_top_1:
    type: grb
    number: 1-30
  l_rollover_top_2:
    type: grb
    number: 1-27
  l_rollover_top_3:
    type: grb
    number: 1-31
  l_rollover_top_4:
    type: grb
    number: 1-28
  l_rollover_top_5:
    type: grb
    number: 1-32
  l_rollover_top_6:
    type: grb
    number: 1-29
  l_rollover_top_7:
    type: grb
    number: 1-33
  l_hole_score_lane_1:
    type: grb
    number: 1-17
    tags:
    - tag_hole_score
  l_hole_score_lane_2:
    type: grb
    number: 1-18
    tags:
    - tag_hole_score
  l_hole_score_lane_3:
    type: grb
    number: 1-19
    tags:
    - tag_hole_score
  l_hole_score_lane_4:
    type: grb
    number: 1-20
    tags:
    - tag_hole_score
  l_hole_score_lane_5:
    type: grb
    number: 1-21
    tags:
    - tag_hole_score
  l_hole_score_lane_6:
    type: grb
    number: 1-22
    tags:
    - tag_hole_score
  l_hole_score_lane_7:
    type: grb
    number: 1-23
    tags:
    - tag_hole_score
  l_hole_score_lane_8:
    type: grb
    number: 1-24
    tags:
    - tag_hole_score
  l_hole_score_lane_9:
    type: grb
    number: 1-25
    tags:
    - tag_hole_score
  l_hole_score_lane_10:
    type: grb
    number: 1-26
    tags:
    - tag_hole_score
  # Explosion Bonus
  l_explosion_1:
    type: grb
    number: 1-11
  l_explosion_2:
    type: grb
    number: 1-10
  l_explosion_3:
    type: grb
    number: 1-12
  l_explosion_4:
    type: grb
    number: 1-7
  l_explosion_5:
    type: grb
    number: 1-6
  l_explosion_6:
    type: grb
    number: 1-8
  l_explosion_7:
    type: grb
    number: 1-5
  l_explosion_8:
    type: grb
    number: 1-9
  l_explosion_9:
    type: grb
    number: 1-13
  l_explosion_10:
    type: grb
    number: 1-14
  # Pop Bumper 1 Ring
  l_bumper1_1:
    number: 2-1
  l_bumper1_2:
    number: 2-2
  l_bumper1_3:
    number: 2-3
  l_bumper1_4:
    number: 2-4
  l_bumper1_5:
    number: 2-5
  l_bumper1_6:
    number: 2-6
  l_bumper1_7:
    number: 2-7
  l_bumper1_8:
    number: 2-8
  l_bumper1_9:
    number: 2-9
  l_bumper1_10:
    number: 2-10
  l_bumper1_11:
    number: 2-11
  l_bumper1_12:
    number: 2-12
  l_bumper1_13:
    number: 2-13
  l_bumper1_14:
    number: 2-14
  l_bumper1_15:
    number: 2-15
  l_bumper1_16:
    number: 2-16
  l_bumper1_17:
    number: 2-17
  l_bumper1_18:
    number: 2-18
  l_bumper1_19:
    number: 2-19
  l_bumper1_20:
    number: 2-20
  l_bumper1_21:
    number: 2-21
  l_bumper1_22:
    number: 2-22
  l_bumper1_23:
    number: 2-23
  l_bumper1_24:
    number: 2-24
  # Pop Bumper 2 Ring
  l_bumper2_1:
    number: 2-25
  l_bumper2_2:
    number: 2-26
  l_bumper2_3:
    number: 2-27
  l_bumper2_4:
    number: 2-28
  l_bumper2_5:
    number: 2-29
  l_bumper2_6:
    number: 2-30
  l_bumper2_7:
    number: 2-31
  l_bumper2_8:
    number: 2-32
  l_bumper2_9:
    number: 2-33
  l_bumper2_10:
    number: 2-34
  l_bumper2_11:
    number: 2-35
  l_bumper2_12:
    number: 2-36
  l_bumper2_13:
    number: 2-37
  l_bumper2_14:
    number: 2-38
  l_bumper2_15:
    number: 2-39
  l_bumper2_16:
    number: 2-40
  l_bumper2_17:
    number: 2-41
  l_bumper2_18:
    number: 2-42
  l_bumper2_19:
    number: 2-43
  l_bumper2_20:
    number: 2-44
  l_bumper2_21:
    number: 2-45
  l_bumper2_22:
    number: 2-46
  l_bumper2_23:
    number: 2-47
  l_bumper2_24:
    number: 2-48
  # Pop Bumper 2 Ring
  l_bumper3_1:
    number: 3-1
  l_bumper3_2:
    number: 3-2
  l_bumper3_3:
    number: 3-3
  l_bumper3_4:
    number: 3-4
  l_bumper3_5:
    number: 3-5
  l_bumper3_6:
    number: 3-6
  l_bumper3_7:
    number: 3-7
  l_bumper3_8:
    number: 3-8
  l_bumper3_9:
    number: 3-9
  l_bumper3_10:
    number: 3-10
  l_bumper3_11:
    number: 3-11
  l_bumper3_12:
    number: 3-12
  l_bumper3_13:
    number: 3-13
  l_bumper3_14:
    number: 3-14
  l_bumper3_15:
    number: 3-15
  l_bumper3_16:
    number: 3-16
  l_bumper3_17:
    number: 3-17
  l_bumper3_18:
    number: 3-18
  l_bumper3_19:
    number: 3-19
  l_bumper3_20:
    number: 3-20
  l_bumper3_21:
    number: 3-21
  l_bumper3_22:
    number: 3-22
  l_bumper3_23:
    number: 3-23
  l_bumper3_24:
    number: 3-24
