#config_version=4
displays:
  # window needed without physical DMD
  dmd:
    width: 128
    height: 32
    default: true
  window:
    # seems bound to 16x10ish aspect
    width: 1920
    height: 1080

window:
  width: 1920
  height: 1080
  title: Immortal Combat
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: window
