#config_version=4
leds:
  l_bumper_1:
    number:
  l_bumper_2:
    number:
  l_bumper_3:
    number:
  l_hole_score_lane_1:
    number:
  l_hole_score_lane_2:
    number:
  l_hole_score_lane_3:
    number:
  l_hole_score_lane_4:
    number:
  l_hole_score_lane_5:
    number:
  l_hole_score_lane_6:
    number:
  l_hole_score_lane_7:
    number:
  l_hole_score_lane_8:
    number:
  l_hole_score_lane_9:
    number:
  l_hole_score_lane_10:
    number:
  l_explosion_1:
    number:
  l_explosion_2:
    number:
  l_explosion_3:
    number:
  l_explosion_4:
    number:
  l_explosion_5:
    number:
  l_explosion_6:
    number:
  l_explosion_7:
    number:
  l_explosion_8:
    number:
  l_explosion_9:
    number:
  l_explosion_10:
    number:
