#config_version=4
# all switches left to right
switches:
  s_plunger_lane:
    number:
    tags: launch
  # Trough Switches (max 3 balls, "duo-multi" and "extra")
  s_trough_1:
    number:
  s_trough_2:
    number:
  s_trough_3:
    number:
  s_trough_jam:
    number:
  # Pop Bumpers
  s_kicker_saucer:
    number:
    tags: playfield_active
  s_kicker_gun:
    number:
    tags: playfield_active
  s_knocker:
    number:
    tags: playfield_active
  s_bumper_1:
    number:
    tags: playfield_active
  s_bumper_2:
    number:
    tags: playfield_active
  s_bumper_3:
    number:
    tags: playfield_active
  s_slingshot_1:
    number:
    tags: playfield_active
  s_slingshot_2:
    number:
    tags: playfield_active
  s_flipper_1:
    number:
  s_flipper_2:
    number:
  s_spinner_1:
    number:
    tags: playfield_active
  s_rollover_top_1:
    number:
    tags: playfield_active
  s_rollover_top_2:
    number:
    tags: playfield_active
  s_rollover_top_3:
    number:
    tags: playfield_active
  s_rollover_top_4:
    number:
    tags: playfield_active
  s_rollover_top_5:
    number:
    tags: playfield_active
  s_rollover_north_6:
    number:
    tags: playfield_active
  s_rollover_north_7:
    number:
    tags: playfield_active
  s_rollover_bonus_ball_1:
    number:
    tags: playfield_active
  s_rollover_bonus_ball_2:
    number:
    tags: playfield_active
  s_rollover_advance_hole_1:
    number:
    tags: playfield_active
  s_rollover_advance_hole_2:
    number:
    tags: playfield_active
  s_stationary_northwest:
    number:
    tags: playfield_active
  s_stationary_special:
    number:
    tags: playfield_active
  s_drop_target_1:
    number:
    tags: playfield_active
  s_drop_target_2:
    number:
    tags: playfield_active
  s_drop_target_3:
    number:
    tags: playfield_active
  s_drop_target_4:
    number:
    tags: playfield_active
  s_drop_target_5:
    number:
    tags: playfield_active
  s_stationary_advance_bonus:
    number:
    tags: playfield_active
  s_stationary_advance_hole_score:
    number:
    tags: playfield_active
  s_start:
    number:
    # 'start' tag is important
    tags: start
