# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Combat Pinball

on:
  push:
    branches: [ "v0.33" ]
  pull_request:
    branches: [ "v0.33" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        sudo apt-get install \
          build-essential git \
          zlib1g-dev libjpeg-dev libtiff5-dev libtiff5-dev \
          libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev \
          libsdl2-mixer-dev gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-base gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly libgstreamer1.0-dev \
          libxine2-ffmpeg libsmpeg-dev libswscale-dev \
          libavformat-dev libavcodec-dev libjpeg-dev libtiff5-dev \
          libx11-dev libmtdev-dev build-essential libgl1-mesa-dev \
          libgles2-mesa-dev pulseaudio lsb-release \
          libgl1-mesa-dri libavfilter-dev libavdevice-dev libunwind-dev -y
    - name: Install app dependencies
      run: |
        curl https://pyenv.run | bash
        export PYENV_ROOT="$HOME/.pyenv"
        [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv install 3.6
        pyenv global 3.6
        pip install --upgrade pip setuptools wheel build coveralls pillow
        pip install --upgrade Cython==0.25.2
        pip install mpf==0.33.49
        pip install mpf-mc==0.33.16
    - name: Test
      run: |
        python -m unittest tests/*.py
