#config_version=4
mode:
  start_events:
    s_kicker_gun_active
    s_kicker_missile_active
  stop_events:
    timer_flash_score_complete
    mode_high_score_started
    mode_attract_started
    ball_will_end
    game_ended
  priority: 125

timers:
  flash_score:
    start_value: 0
    end_value: 15
    direction: up
    start_running: true
    control_events:
      - event: timer_flash_score_complete
        action: reset
      - event: timer_flash_score_complete
        action: stop
      - event: ball_will_end
        action: stop

show_player:
  mode_flash_score_started:
    bumper_flash:
      action: play

led_player:
  mode_flash_score_started:
    l_spinner: white
  mode_flash_score_stopped:
    l_spinner: 000000

scoring:
  s_bumper_1_active:
    score: 1000|block
  s_bumper_2_active:
    score: 1000|block
  s_bumper_3_active:
    score: 1000|block
  s_spinner_active:
    score: 1000|block
